#!/bin/bash

## COMMERCE Platform package, v1.0
##
## @author Ivan Berezhnov ivan.berezhnov@icloud.com
##
## Docksal custom command rebuild script
## Syncs DB from production.
## Runs composer, drush cim, drush updb, drush cr
## Builds theme @see scripts/build_theme.sh
##
## Usage: fin rebuild


# Trapping CTRL-C
trap ctrl_c INT
trap ctrl_c SIGINT
trap ctrl_c SIGTERM
# trap ctrl-c and call ctrl_c()
function ctrl_c() {
    echo-red "\n Canceled, deleting DB dump if any"
    rm -f $PROJECT_ROOT/dbs/*.sql.gz
    echo-red "Good bye."
    exit $?
}

#Paths and environment settings
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
MAIN_THEME_PATH="${DOCROOT_PATH}/themes/commerce"
TOOLL_THEME_PATH="${DOCROOT_PATH}/themes/tooll"
WINSPORT_THEME_PATH="${DOCROOT_PATH}/themes/winsport"

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions for console output
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#Show some art
clear
cat "${PROJECT_ROOT}/build-scripts/ascii.txt"

#Database extcation
echo-yellow "#### Copy site settings file for developing..."
rm $PROJECT_ROOT/docroot/sites/tooll.shop/settings.local.php
rm $PROJECT_ROOT/docroot/sites/winsport.shop/settings.local.php
cp $PROJECT_ROOT/.docksal/examples/tooll/settings.local.php $PROJECT_ROOT/docroot/sites/tooll.shop/
cp $PROJECT_ROOT/.docksal/examples/winsport/settings.local.php $PROJECT_ROOT/docroot/sites/winsport.shop/
echo-green "Done.\n"

# Database download
echo-yellow "#### Downloading Database from server, please wait. This might take a while..."
rm -f $PROJECT_ROOT/dbs/*.sql.gz
rm -f $PROJECT_ROOT/dbs/*.sql

# We nee do catch error if any
set +e

#fin terminus backup:get --element=db $PANTHEON_ENV --to=/var/www/db/database.sql.gz
scp sportb07@sportb07.ftp.tools:./commerce8.shop/www/dbs/*.sql.gz  $PROJECT_ROOT/dbs
if [ $? -ne 0 ] ; then
    echo-red "## Interrupted ## \n"
    echo-red "Error downloading database from server."
    exit $?
else
    echo-green "Done. Downloaded to ${PROJECT_ROOT}/dbs/\n"
fi

# Abort if anything fails
set -e

#Database extcation
echo-yellow "#### Extracting..."
gunzip $PROJECT_ROOT/dbs/*.sql.gz
echo-green "Done.\n"

#Set permissions
echo-yellow "#### Making site directory writable..."
chmod -R 777 $PROJECT_ROOT/dbs/
echo-green "Done.\n"

#Create databases
echo-yellow "#### Create dbs..."
fin db drop default
fin db drop winsport
fin db drop tooll
fin db create winsport
fin db create tooll
echo-green "Done.\n"

#Database import
echo-yellow "#### Importing..."
fin db import $PROJECT_ROOT/dbs/winsport.sql --db=winsport
fin db import $PROJECT_ROOT/dbs/tooll.sql --db=tooll

#Removing unnecessary sql dump files
echo-yellow "#### Removing files..."
rm -f $PROJECT_ROOT/dbs/*.sql
echo-green "Done.\n"

#Running composer
echo-yellow "#### Running composer install"
cd $PROJECT_ROOT
fin exec composer install
echo-green "Done.\n"

#Running Drush commands
echo-yellow "#### Running drush cim, drush updb, drush cr"
cd $DOCROOT_PATH
fin drush updb -y -l winsport.shop
fin drush cim -y -l winsport.shop
fin drush cr -l winsport.shop

fin drush updb -y -l tooll.shop
fin drush cim -y -l tooll.shop
fin drush cr -l tooll.shop
echo-green "Done.\n"

#Building theme
echo-yellow "#### Running gulp tasks in theme ${MAIN_THEME}"
if [ -e "$MAIN_THEME_PATH/package-lock.json" ]; then
    echo-yellow "package-lock.json is available, running npm, bower and gulp...\n"
    cd $MAIN_THEME_PATH
    cd $TOOLL_THEME_PATH
    cd $WINSPORT_THEME_PATH
    #fin exec bash -i /var/www/scripts/build_theme.sh
else
    echo-yellow "package-lock.json is not available, deleting node_modules and npm install\n"
    rm -rf $MAIN_THEME_PATH/node_modules
    rm -rf $TOOLL_THEME_PATH/node_modules
    rm -rf $WINSPORT_THEME_PATH/node_modules
    cd $MAIN_THEME_PATH
    cd $TOOLL_THEME_PATH
    cd $WINSPORT_THEME_PATH
    #fin exec bash -i /var/www/scripts/build_theme.sh
fi

echo-green "https://winsport.shop.docksal/\n"
echo-green "https://tooll.shop.docksal/\n"

echo-green " <<<<<<< Rebuild is complete >>>>>>> "
