#!/bin/bash

## SHOPS Docksal package, v1.0
##
## @author Ivan Berezhnov <ivan.berezhnov@icloud.com>
##
## Docksal custom command rebuild script
## Syncs DB from Host environment.
## Runs composer, drush cim, drush updb, drush cr
## Builds theme @see fin gulp
##
## Usage: fin rebuild


# Trapping CTRL-C
trap ctrl_c INT
trap ctrl_c SIGINT
trap ctrl_c SIGTERM
# trap ctrl-c and call ctrl_c()
function ctrl_c() {
    echo-red "\n Canceled, deleting DB dump if any"
    rm -f $PROJECT_ROOT/db/database.sql.gz
    echo-red "Good bye."
    exit $?
}

# Paths and environment settings
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
MAIN_THEME_PATH="${DOCROOT_PATH}/themes/${THEME_NAME}"
THEME_PATH_INSIDE_CONTAINER="/var/www/${DOCROOT}/themes/${THEME_NAME}"
URL_SB="sb.${VIRTUAL_HOST}"
URL_TL="tl.${VIRTUAL_HOST}"
URL_WIN="win.${VIRTUAL_HOST}"

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

# Helper functions for console output
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#Show some art
clear
cat "${PROJECT_ROOT}/build-scripts/ascii.txt"

# Abort if anything fails
set -e

# Running composer
echo-yellow "Running composer install"
cd $PROJECT_ROOT
fin exec composer install
echo-green "Done.\n"

echo-yellow "Configuration file for multi-site..."
echo "<?php" > $DOCROOT_PATH/sites/sites.local.php
echo "\$sites['${URL_SB}'] = 'sportbaza';" >> $DOCROOT_PATH/sites/sites.php
echo "\$sites['${URL_TL}'] = 'tooll';" >> $DOCROOT_PATH/sites/sites.php
echo "\$sites['${URL_WIN}'] = 'winsport';" >> $DOCROOT_PATH/sites/sites.php
echo " " >> $DOCROOT_PATH/sites/sites.php
cat $DOCROOT_PATH/sites/sites.php
echo-green "Done.\n"

echo-yellow "Remove dbs..."
fin db drop default
fin db drop sportbaza
fin db drop tooll
fin db drop winsport
echo-green "Done.\n"

echo-yellow "Create dbs..."
fin db create sportbaza
fin db create tooll
fin db create winsport
echo-green "Done.\n"

echo-yellow "Import dbs..."
fin db import $PROJECT_ROOT/db/default_sportbaza.sql --db=sportbaza --db-user=user --db-password=user
fin db import $PROJECT_ROOT/db/default_tooll.sql --db=tooll --db-user=user --db-password=user
fin db import $PROJECT_ROOT/db/default_winsport.sql --db=winsport --db-user=user --db-password=user
echo-green "\n"

# Running Drush commands
echo-yellow "Running drush cim, drush updb, drush cr"
echo-yellow " > sportbaza"
cd $DOCROOT_PATH
fin drush updb -y --uri=$URL_SB
fin drush cim -y --uri=$URL_SB
fin drush cr --uri=$URL_SB
echo-yellow " > tooll"
fin drush updb -y --uri=$URL_TL
fin drush cim -y --uri=$URL_TL
fin drush cr --uri=$URL_TL
echo-yellow " > winsport"
fin drush updb -y --uri=$URL_WIN
fin drush cim -y --uri=$URL_WIN
fin drush cr --uri=$URL_WIN
echo-green "Done.\n"

## Building theme
echo-yellow "Running gulp tasks in theme ${MAIN_THEME}"
#fin gulp build

echo-green " <<<<<<< Rebuild is complete >>>>>>> "

echo-green " You can open: http://${URL_SB}${NC} "
echo-green "               http://${URL_TL}${NC} "
echo-green "               http://${URL_WIN}${NC} "
echo
